server:
  port: 8090
  servlet:
    session:
      tracking-modes: cookie

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: portfolio_user
    password: portfolio
    driver-class-name: oracle.jdbc.driver.OracleDriver

  profiles:
    include: info

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.portfolio.board.DTO
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: DEBUG